# Generated by Django 4.2.7 on 2023-11-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BadSantas',
            fields=[
                ('BadSantaId', models.AutoField(primary_key=True, serialize=False)),
                ('BadSantaName', models.CharField(max_length=100)),
                ('BadSantaPlace', models.CharField(max_length=3)),
                ('Draw', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Draws',
            fields=[
                ('DrawId', models.AutoField(primary_key=True, serialize=False)),
                ('DrawTotal', models.CharField(max_length=3)),
            ],
        ),
    ]
